_lab_members/undergraduate/hongvan_pham.md
=> update Hong Van Pham lab member page

_lab_members/undergraduate/jinho_yoon.md
Fixes #29 .
Hope everything is okay!
=> Add Jinho Yoon to the Lab Members page.

_lab_members/undergraduate/khoi_nguyen.md
=> Add Khoi Nguyen to Lab Members page.

_lab_members/masters/wanyi_lin.md
Fix #45
Add github account to wanyi_lin.md
=> Add github account to wanyi_lin.md

_lab_members/undergraduate/katie_lin.md
=> Added Katie to Undergraduates section

_lab_members/undergraduate/max_zhang.md
=> add max zhang lab member md and profile pic

_people/lab-members/jacob_degroot-maggetti.md
=> add profile for jacob to lab-members

_lab_members/undergraduate/jiwoo_jeong.md
=> added Jiwoo to the lab members' page

_lab_members/undergraduate/zhanna_klimanova.md
Adding minimalist profile information for group website.
=> Add profile information.

_lab_members/masters/jacob_degroot-maggetti.md
This PR updates my blurb on the website.
It also updates several of the variables associated with my page, adding a `photo`, `current_focus` and `academic_record`.
=> Update Jacob's blurb

_lab_members/masters/jacob_degroot-maggetti.md
It turns out `placeholder.jpg` doesn't work - it appears it needs to be `placeholder.png`.
=> fix placeholder image for Jacob's page

_lab_members/undergraduate/zhanna_klimanova.md
The --- at the bottom of the page was added to fix formatting issue.
=> Fix bug in markdown formatting

_lab_members/masters/lucas_march.md
tried to fix publication list error shown in md file
=> fix publication list from error in md file

404.html
previous links pointed to my personal repo
=> Update absolute links to point to deployed site

assets/css/main.css
Reformatting the css document to be more visually comprehensive. This was part of the post-deforesting task to reformat the new static pages but this .css page was forgotten - it is being updated now.
=> Reformatting css document

resources/index.html
Link was leading to the wrong page.
=> Fix for wiki link

lab_members/alumni/gabriel_vigliensoni/index.html
In this pull request I'm changing the link to my CV.
=> Fix: New link for CV.

software/index.html, software/neon/index.html
Neon issue https://github.com/DDMAL/Neon/issues/1070
=> Update Neon developers

lab_members/masters/kai_mikkelsen/index.html
Not sure if I did this right, Let me know if theres anything I should change.
=> add kai profile

index.html
- Resolves https://github.com/DDMAL/ddmal.github.io/issues/177
=> Add an alert to homepage about changing domain name

lab_members/masters/caroline_guo/index.html
=> Updating bio.html
